### ISSUE TITLE
Update Google Services dependency to latest 12.0.0 or at least 11.4.0

### ISSUE THREAD

**Issue by damianpetla** [KatalysatorAB/GlimrSDK-Android#2]
Is there any plan to update Google Services dependency. Version 10.2.+ is pretty outdated.

**Comment by svenroed** [comment]
there will be a new lite version specifically for you within the next days. we will reach out with more info.

**Comment by svenroed** [comment]
this version might be more interesting for your use case specifically `compile 'io.glimr.geo:glimr-sdk-lite:3.0.1'`
